/*
 * Copyright (C) 2016 Beat Luginbühl <lugi@lugipfupf.ch>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.openbravo.pos.imports;

import com.openbravo.data.gui.Populator;
import com.openbravo.pos.forms.AppLocal;
import javax.swing.JPanel;

/**
 *
 * @author Beat Luginbühl <lugi@lugipfupf.ch>
 */
public class JPanelCustomerFields extends JPanel implements Populator {

    /**
     * Creates new form JPanelCustomers
     */
    public JPanelCustomerFields() {
        initComponents();
    }
    
    @Override
    public int populate() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFields = new javax.swing.JPanel();
        lblCard = new javax.swing.JLabel();
        cmbCard = new javax.swing.JComboBox<>();
        chkCardGenerate = new javax.swing.JCheckBox();
        lblDummy = new javax.swing.JLabel();
        lblAccountId = new javax.swing.JLabel();
        cmbAccountId = new javax.swing.JComboBox<>();
        lblSearchKey = new javax.swing.JLabel();
        cmdSearchKey = new javax.swing.JComboBox<>();
        lblFirstName = new javax.swing.JLabel();
        cmbFirstName = new javax.swing.JComboBox<>();
        lblTaxCat = new javax.swing.JLabel();
        cmbTaxCat = new javax.swing.JComboBox<>();
        lblLastName = new javax.swing.JLabel();
        cmbLastName = new javax.swing.JComboBox<>();
        lblCreditLimit = new javax.swing.JLabel();
        cmbCreditLimit = new javax.swing.JComboBox<>();
        lblEmail = new javax.swing.JLabel();
        cmbEmail = new javax.swing.JComboBox<>();
        lblPhone1 = new javax.swing.JLabel();
        cmdPhone1 = new javax.swing.JComboBox<>();
        lblPhone2 = new javax.swing.JLabel();
        cmbPhone2 = new javax.swing.JComboBox<>();
        lblFax = new javax.swing.JLabel();
        cmdFax = new javax.swing.JComboBox<>();
        lblAddress1 = new javax.swing.JLabel();
        cmbAddress1 = new javax.swing.JComboBox<>();
        lblAddress2 = new javax.swing.JLabel();
        cmbAddress2 = new javax.swing.JComboBox<>();
        lblCity = new javax.swing.JLabel();
        cmbCity = new javax.swing.JComboBox<>();
        lblRegion = new javax.swing.JLabel();
        cmbRegion = new javax.swing.JComboBox<>();
        lblZip = new javax.swing.JLabel();
        cmbZip = new javax.swing.JComboBox<>();
        lblCountry = new javax.swing.JLabel();
        cmbCountry = new javax.swing.JComboBox<>();
        lblNotes = new javax.swing.JLabel();
        cmbNotes = new javax.swing.JComboBox<>();
        lblVisible = new javax.swing.JLabel();
        cmbVisible = new javax.swing.JComboBox<>();
        pnlData = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        pnlFields.setLayout(new java.awt.GridLayout(0, 4, 10, 0));

        lblCard.setText(AppLocal.getIntString("label.card")); // NOI18N
        pnlFields.add(lblCard);

        cmbCard.setEnabled(false);
        pnlFields.add(cmbCard);

        chkCardGenerate.setSelected(true);
        chkCardGenerate.setText(AppLocal.getIntString("label.generate")); // NOI18N
        chkCardGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCardGenerateActionPerformed(evt);
            }
        });
        pnlFields.add(chkCardGenerate);
        pnlFields.add(lblDummy);

        lblAccountId.setText(AppLocal.getIntString("label.taxid")); // NOI18N
        pnlFields.add(lblAccountId);

        pnlFields.add(cmbAccountId);

        lblSearchKey.setText(AppLocal.getIntString("label.searchkey")); // NOI18N
        pnlFields.add(lblSearchKey);

        pnlFields.add(cmdSearchKey);

        lblFirstName.setText(AppLocal.getIntString("label.firstname")); // NOI18N
        pnlFields.add(lblFirstName);

        pnlFields.add(cmbFirstName);

        lblTaxCat.setText(AppLocal.getIntString("label.custtaxcategory")); // NOI18N
        pnlFields.add(lblTaxCat);

        pnlFields.add(cmbTaxCat);

        lblLastName.setText(AppLocal.getIntString("label.lastname")); // NOI18N
        pnlFields.add(lblLastName);

        pnlFields.add(cmbLastName);

        lblCreditLimit.setText(AppLocal.getIntString("label.maxdebt")); // NOI18N
        pnlFields.add(lblCreditLimit);

        pnlFields.add(cmbCreditLimit);

        lblEmail.setText(AppLocal.getIntString("label.email")); // NOI18N
        pnlFields.add(lblEmail);

        pnlFields.add(cmbEmail);

        lblPhone1.setText(AppLocal.getIntString("label.phone")); // NOI18N
        pnlFields.add(lblPhone1);

        pnlFields.add(cmdPhone1);

        lblPhone2.setText(AppLocal.getIntString("label.phone2")); // NOI18N
        pnlFields.add(lblPhone2);

        pnlFields.add(cmbPhone2);

        lblFax.setText(AppLocal.getIntString("label.fax")); // NOI18N
        pnlFields.add(lblFax);

        pnlFields.add(cmdFax);

        lblAddress1.setText(AppLocal.getIntString("label.address")); // NOI18N
        pnlFields.add(lblAddress1);

        pnlFields.add(cmbAddress1);

        lblAddress2.setText(AppLocal.getIntString("label.address2")); // NOI18N
        pnlFields.add(lblAddress2);

        pnlFields.add(cmbAddress2);

        lblCity.setText(AppLocal.getIntString("label.city")); // NOI18N
        pnlFields.add(lblCity);

        pnlFields.add(cmbCity);

        lblRegion.setText(AppLocal.getIntString("label.region")); // NOI18N
        pnlFields.add(lblRegion);

        pnlFields.add(cmbRegion);

        lblZip.setText(AppLocal.getIntString("label.postal")); // NOI18N
        pnlFields.add(lblZip);

        pnlFields.add(cmbZip);

        lblCountry.setText(AppLocal.getIntString("label.country")); // NOI18N
        pnlFields.add(lblCountry);

        pnlFields.add(cmbCountry);

        lblNotes.setText(AppLocal.getIntString("label.notes")); // NOI18N
        pnlFields.add(lblNotes);

        pnlFields.add(cmbNotes);

        lblVisible.setText(AppLocal.getIntString("label.visible")); // NOI18N
        pnlFields.add(lblVisible);

        pnlFields.add(cmbVisible);

        add(pnlFields);

        pnlData.setLayout(new java.awt.BorderLayout());

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblData);

        pnlData.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(pnlData);
    }// </editor-fold>//GEN-END:initComponents

    private void chkCardGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCardGenerateActionPerformed
        cmbCard.setEnabled(!chkCardGenerate.isSelected());
    }//GEN-LAST:event_chkCardGenerateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkCardGenerate;
    private javax.swing.JComboBox<String> cmbAccountId;
    private javax.swing.JComboBox<String> cmbAddress1;
    private javax.swing.JComboBox<String> cmbAddress2;
    private javax.swing.JComboBox<String> cmbCard;
    private javax.swing.JComboBox<String> cmbCity;
    private javax.swing.JComboBox<String> cmbCountry;
    private javax.swing.JComboBox<String> cmbCreditLimit;
    private javax.swing.JComboBox<String> cmbEmail;
    private javax.swing.JComboBox<String> cmbFirstName;
    private javax.swing.JComboBox<String> cmbLastName;
    private javax.swing.JComboBox<String> cmbNotes;
    private javax.swing.JComboBox<String> cmbPhone2;
    private javax.swing.JComboBox<String> cmbRegion;
    private javax.swing.JComboBox<String> cmbTaxCat;
    private javax.swing.JComboBox<String> cmbVisible;
    private javax.swing.JComboBox<String> cmbZip;
    private javax.swing.JComboBox<String> cmdFax;
    private javax.swing.JComboBox<String> cmdPhone1;
    private javax.swing.JComboBox<String> cmdSearchKey;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAccountId;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblAddress2;
    private javax.swing.JLabel lblCard;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblCreditLimit;
    private javax.swing.JLabel lblDummy;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblPhone1;
    private javax.swing.JLabel lblPhone2;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JLabel lblSearchKey;
    private javax.swing.JLabel lblTaxCat;
    private javax.swing.JLabel lblVisible;
    private javax.swing.JLabel lblZip;
    private javax.swing.JPanel pnlData;
    private javax.swing.JPanel pnlFields;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables

    
}
