/*
 * Copyright (C) 2016 Beat Luginbühl <lugi@lugipfupf.ch>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.openbravo.pos.imports;

import com.openbravo.pos.forms.AppLocal;

public class JPanelCSVFileChooser extends javax.swing.JPanel {

    /**
     *
     */
    public JPanelCSVFileChooser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFile = new javax.swing.JLabel();
        txtFile = new javax.swing.JTextField();
        btnFile = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblConfig = new javax.swing.JLabel();
        lblDelim = new javax.swing.JLabel();
        txtDelim = new javax.swing.JTextField();
        lblQuote = new javax.swing.JLabel();
        txtQuote = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(186, 84));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        lblFile.setText(AppLocal.getIntString("label.csvfile")); // NOI18N
        lblFile.setPreferredSize(new java.awt.Dimension(80, 16));
        lblFile.setRequestFocusEnabled(false);
        jPanel1.add(lblFile);

        txtFile.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel1.add(txtFile);

        btnFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/fileopen.png"))); // NOI18N
        btnFile.setToolTipText(AppLocal.getIntString("label.csvfile")); // NOI18N
        btnFile.setPreferredSize(new java.awt.Dimension(64, 32));
        jPanel1.add(btnFile);

        btnRead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/ok.png"))); // NOI18N
        btnRead.setToolTipText(AppLocal.getIntString("label.csvread")); // NOI18N
        btnRead.setPreferredSize(new java.awt.Dimension(64, 32));
        jPanel1.add(btnRead);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        lblConfig.setText(AppLocal.getIntString("label.options")); // NOI18N
        lblConfig.setPreferredSize(new java.awt.Dimension(80, 16));
        jPanel2.add(lblConfig);

        lblDelim.setText(AppLocal.getIntString("label.csvdelimit")); // NOI18N
        jPanel2.add(lblDelim);

        txtDelim.setText(",");
        txtDelim.setPreferredSize(new java.awt.Dimension(32, 28));
        jPanel2.add(txtDelim);

        lblQuote.setText(AppLocal.getIntString("label.csvquote")); // NOI18N
        jPanel2.add(lblQuote);

        txtQuote.setText("\"");
        txtQuote.setPreferredSize(new java.awt.Dimension(32, 28));
        jPanel2.add(txtQuote);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFile;
    private javax.swing.JButton btnRead;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblConfig;
    private javax.swing.JLabel lblDelim;
    private javax.swing.JLabel lblFile;
    private javax.swing.JLabel lblQuote;
    private javax.swing.JTextField txtDelim;
    private javax.swing.JTextField txtFile;
    private javax.swing.JTextField txtQuote;
    // End of variables declaration//GEN-END:variables
}
